kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: test-demo-
  namespace: jdavies47
spec:
  params:
  - name: portfolio
    value: galasa/my-app-core-regression.yaml
  - name: refspec
    value: +refs/heads/main:refs/heads/main
  pipelineRef:
    name: github-pr-pipeline
  serviceAccountName: demo-build-bot
  podTemplate:
    nodeSelector:
      kubernetes.io/arch: amd64
  workspaces:
  - name: git-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn-temp